// Translation system for all UI text
const translations = {
  en: {
    // Headers and Titles
    "definitions-history": "Definitions History",
    "game-info": "Game Info",
    "scores": "Scores",
    "player": "Player",
    "computer": "Computer",
    "tiles-remaining": "Tiles Remaining",
    "exchange-tiles": "Exchange Tiles",
    "activate-exchange": "Activate Exchange Portal",
    "exchange-instructions": "Drag tiles here to exchange them",
    
    // Buttons
    "print-history": "Print Definition History (Shows Word Definitions)",
    "submit": "Submit",
    "shuffle-rack": "Shuffle Rack",
    "skip-turn": "Skip Turn",
    "how-to-play": "How to Play",
    "quit-game": "Quit / End Game",
    "close-menu": "Close menu",
    
    // Mobile Notifications
    "landscape-notice": "For the best experience, please rotate your device to landscape mode",
    "scroll-notice": "You can scroll up and down to access your rack, game controls, and move history",
    "instruction-notice": "Please read \"How to Play\" in the menu before starting",
    
    // Instructions
    "how-to-play-title": "How to Play",
    "playing-tiles": "1. Playing Tiles:",
    "playing-tiles-1": "On desktop: Click and drag tiles from your rack to the board",
    "playing-tiles-2": "On mobile: Touch and hold a tile for 1 second, then drag to place it",
    "playing-tiles-3": "To remove a tile, drag it back to your rack",
    "creating-words": "2. Creating Words:",
    "creating-words-1": "Place tiles horizontally (left to right) or vertically (top to bottom)",
    "creating-words-2": "First word must cross the center star",
    "creating-words-3": "New words must connect to existing tiles on the board",
    "creating-words-4": "All words formed must be valid dictionary words",
    "submitting-move": "3. Submitting Your Move:",
    "submitting-move-1": "After placing your tiles, click the \"Submit\" button",
    "submitting-move-2": "Invalid words will be rejected and tiles returned to your rack",
    "submitting-move-3": "Points will be automatically calculated and added to your score",
    "exchanging-tiles": "4. Exchanging Tiles:",
    "exchanging-tiles-1": "Click \"Activate Exchange Portal\" to start an exchange",
    "exchanging-tiles-2": "Drag unwanted tiles into the portal",
    "exchanging-tiles-3": "You'll receive the same number of new tiles",
    "exchanging-tiles-4": "This counts as your turn",
    "skipping-end": "5. Skipping and Game End:",
    "skipping-end-1": "Use \"Skip Turn\" if you can't make a valid move",
    "skipping-end-2": "The game ends when all tiles are used or both players skip twice in a row",
    "skipping-end-3": "Your score is based on the letter values and bonus squares",
    
    // Dynamic content (generated by JavaScript)
    "console": "Console",
    "copy-all": "Copy All",
    "hint-short-words": "Short words like 'QI', 'ZA', and 'JO' are valid and useful.",
    
    // Toast/Alert messages
    "invalid-word": "Invalid word! Please try again.",
    "copied-clipboard": "Console copied to clipboard!",
    "no-messages-copy": "No messages to copy",
    "place-tiles-first": "Please place some tiles first!",
    
    // Game messages
    "click-change-language": "Click to change language"
  },
  
  es: {
    // Headers and Titles
    "definitions-history": "Historial de Definiciones",
    "game-info": "Información del Juego",
    "scores": "Puntuaciones",
    "player": "Jugador",
    "computer": "Computadora",
    "tiles-remaining": "Fichas Restantes",
    "exchange-tiles": "Intercambiar Fichas",
    "activate-exchange": "Activar Portal de Intercambio",
    "exchange-instructions": "Arrastra fichas aquí para intercambiarlas",
    
    // Buttons
    "print-history": "Imprimir Historial de Definiciones (Muestra Definiciones de Palabras)",
    "submit": "Enviar",
    "shuffle-rack": "Mezclar Bandeja",
    "skip-turn": "Saltar Turno",
    "how-to-play": "Cómo Jugar",
    "quit-game": "Salir / Terminar Juego",
    "close-menu": "Cerrar menú",
    
    // Mobile Notifications
    "landscape-notice": "Para la mejor experiencia, gira tu dispositivo a modo paisaje",
    "scroll-notice": "Puedes desplazarte hacia arriba y hacia abajo para acceder a tu bandeja, controles del juego e historial de movimientos",
    "instruction-notice": "Por favor lee \"Cómo Jugar\" en el menú antes de comenzar",
    
    // Instructions
    "how-to-play-title": "Cómo Jugar",
    "playing-tiles": "1. Colocando Fichas:",
    "playing-tiles-1": "En escritorio: Haz clic y arrastra fichas de tu bandeja al tablero",
    "playing-tiles-2": "En dispositivo móvil: Mantén presionada una ficha durante 1 segundo, luego arrástrala para colocarla",
    "playing-tiles-3": "Para quitar una ficha, arrástrala de vuelta a tu bandeja",
    "creating-words": "2. Creando Palabras:",
    "creating-words-1": "Coloca fichas horizontalmente (de izquierda a derecha) o verticalmente (de arriba a abajo)",
    "creating-words-2": "La primera palabra debe cruzar la estrella central",
    "creating-words-3": "Las palabras nuevas deben conectarse con fichas existentes en el tablero",
    "creating-words-4": "Todas las palabras formadas deben ser palabras válidas del diccionario",
    "submitting-move": "3. Enviando Tu Movimiento:",
    "submitting-move-1": "Después de colocar tus fichas, haz clic en el botón \"Enviar\"",
    "submitting-move-2": "Las palabras inválidas serán rechazadas y las fichas devolverán a tu bandeja",
    "submitting-move-3": "Los puntos se calcularán automáticamente y se agregarán a tu puntuación",
    "exchanging-tiles": "4. Intercambiando Fichas:",
    "exchanging-tiles-1": "Haz clic en \"Activar Portal de Intercambio\" para comenzar un intercambio",
    "exchanging-tiles-2": "Arrastra fichas no deseadas al portal",
    "exchanging-tiles-3": "Recibirás el mismo número de fichas nuevas",
    "exchanging-tiles-4": "Esto cuenta como tu turno",
    "skipping-end": "5. Saltar y Fin del Juego:",
    "skipping-end-1": "Usa \"Saltar Turno\" si no puedes hacer un movimiento válido",
    "skipping-end-2": "El juego termina cuando se utilizan todas las fichas o ambos jugadores saltan dos veces seguidas",
    "skipping-end-3": "Tu puntuación se basa en los valores de las letras y los cuadrados bonus",
    
    // Dynamic content (generated by JavaScript)
    "console": "Consola",
    "copy-all": "Copiar Todo",
    "hint-short-words": "Las palabras cortas como 'QI', 'ZA' y 'JO' son válidas y útiles.",
    
    // Toast/Alert messages
    "invalid-word": "¡Palabra inválida! Por favor inténtalo de nuevo.",
    "copied-clipboard": "\u00a1Consola copiada al portapapeles!",
    "no-messages-copy": "No hay mensajes para copiar",
    "place-tiles-first": "¡Por favor coloca algunas fichas primero!",
    
    // Game messages
    "click-change-language": "Haz clic para cambiar idioma"
  },
  
  fr: {
    // Headers and Titles
    "definitions-history": "Historique des Définitions",
    "game-info": "Informations du Jeu",
    "scores": "Scores",
    "player": "Joueur",
    "computer": "Ordinateur",
    "tiles-remaining": "Tuiles Restantes",
    "exchange-tiles": "Échanger les Tuiles",
    "activate-exchange": "Activer le Portail d'Échange",
    "exchange-instructions": "Faites glisser les tuiles ici pour les échanger",
    
    // Buttons
    "print-history": "Imprimer l'Historique des Définitions (Affiche les Définitions des Mots)",
    "submit": "Soumettre",
    "shuffle-rack": "Mélanger le Chevalet",
    "skip-turn": "Sauter le Tour",
    "how-to-play": "Comment Jouer",
    "quit-game": "Quitter / Terminer le Jeu",
    "close-menu": "Fermer le menu",
    
    // Mobile Notifications
    "landscape-notice": "Pour la meilleure expérience, veuillez faire pivoter votre appareil en mode paysage",
    "scroll-notice": "Vous pouvez faire défiler vers le haut et vers le bas pour accéder à votre chevalet, aux contrôles du jeu et à l'historique des mouvements",
    "instruction-notice": "Veuillez lire \"Comment Jouer\" dans le menu avant de commencer",
    
    // Instructions
    "how-to-play-title": "Comment Jouer",
    "playing-tiles": "1. Placer des Tuiles:",
    "playing-tiles-1": "Sur bureau: Cliquez et glissez les tuiles de votre chevalet vers le plateau",
    "playing-tiles-2": "Sur mobile: Touchez et maintenez une tuile pendant 1 seconde, puis glissez-la pour la placer",
    "playing-tiles-3": "Pour retirer une tuile, glissez-la vers votre chevalet",
    "creating-words": "2. Créer des Mots:",
    "creating-words-1": "Placez les tuiles horizontalement (de gauche à droite) ou verticalement (de haut en bas)",
    "creating-words-2": "Le premier mot doit croiser l'étoile centrale",
    "creating-words-3": "Les nouveaux mots doivent se connecter aux tuiles existantes sur le plateau",
    "creating-words-4": "Tous les mots formés doivent être des mots valides du dictionnaire",
    "submitting-move": "3. Soumettre Votre Coup:",
    "submitting-move-1": "Après avoir placé vos tuiles, cliquez sur le bouton \"Soumettre\"",
    "submitting-move-2": "Les mots invalides seront rejetés et les tuiles retourneront à votre chevalet",
    "submitting-move-3": "Les points seront calculés automatiquement et ajoutés à votre score",
    "exchanging-tiles": "4. Échanger des Tuiles:",
    "exchanging-tiles-1": "Cliquez sur \"Activer le Portail d'Échange\" pour commencer un échange",
    "exchanging-tiles-2": "Glissez les tuiles indésirables dans le portail",
    "exchanging-tiles-3": "Vous recevrez le même nombre de nouvelles tuiles",
    "exchanging-tiles-4": "Cela compte comme votre tour",
    "skipping-end": "5. Sauter et Fin du Jeu:",
    "skipping-end-1": "Utilisez \"Sauter le Tour\" si vous ne pouvez pas faire un coup valide",
    "skipping-end-2": "Le jeu se termine lorsque toutes les tuiles sont utilisées ou que les deux joueurs passent deux fois d'affilée",
    "skipping-end-3": "Votre score est basé sur les valeurs des lettres et les cases bonus",
    
    // Dynamic content (generated by JavaScript)
    "console": "Console",
    "copy-all": "Copier Tout",
    "hint-short-words": "Les mots courts comme 'QI', 'ZA' et 'JO' sont valides et utiles.",
    
    // Toast/Alert messages
    "invalid-word": "Mot invalide! Veuillez réessayer.",
    "copied-clipboard": "Console copiée dans le presse-papiers!",
    "no-messages-copy": "Aucun message à copier",
    "place-tiles-first": "Veuillez placer d'abord quelques tuiles!",
    
    // Game messages
    "click-change-language": "Cliquez pour changer de langue"
  },
  
  hi: {
    // Headers and Titles
    "definitions-history": "परिभाषा इतिहास",
    "game-info": "खेल जानकारी",
    "scores": "स्कोर",
    "player": "खिलाड़ी",
    "computer": "कंप्यूटर",
    "tiles-remaining": "शेष टाइलें",
    "exchange-tiles": "टाइलें एक्सचेंज करें",
    "activate-exchange": "एक्सचेंज पोर्टल सक्रिय करें",
    "exchange-instructions": "टाइलों को एक्सचेंज करने के लिए यहां ड्रैग करें",
    
    // Buttons
    "print-history": "परिभाषा इतिहास प्रिंट करें (शब्द परिभाषाएं दिखाता है)",
    "submit": "जमा करें",
    "shuffle-rack": "रैक को शफल करें",
    "skip-turn": "बारी छोड़ें",
    "how-to-play": "कैसे खेलें",
    "quit-game": "छोड़ें / खेल समाप्त करें",
    "close-menu": "मेनू बंद करें",
    
    // Mobile Notifications
    "landscape-notice": "सर्वश्रेष्ठ अनुभव के लिए, कृपया अपने डिवाइस को लैंडस्केप मोड में घुमाएं",
    "scroll-notice": "अपने रैक, गेम नियंत्रण और चाल इतिहास तक पहुंचने के लिए आप ऊपर और नीचे स्क्रॉल कर सकते हैं",
    "instruction-notice": "शुरू करने से पहले कृपया मेनू में \"कैसे खेलें\" पढ़ें",
    
    // Instructions
    "how-to-play-title": "कैसे खेलें",
    "playing-tiles": "1. टाइलें रखना:",
    "playing-tiles-1": "डेस्कटॉप पर: अपने रैक से बोर्ड पर टाइलें क्लिक और ड्रैग करें",
    "playing-tiles-2": "मोबाइल पर: 1 सेकंड के लिए एक टाइल को टच और होल्ड करें, फिर इसे रखने के लिए ड्रैग करें",
    "playing-tiles-3": "एक टाइल को हटाने के लिए, इसे अपने रैक में वापस ड्रैग करें",
    "creating-words": "2. शब्द बनाना:",
    "creating-words-1": "टाइलें क्षैतिज (बाएं से दाएं) या लंबवत (ऊपर से नीचे) रखें",
    "creating-words-2": "पहला शब्द केंद्र सितारे को पार करना चाहिए",
    "creating-words-3": "नए शब्दों को बोर्ड पर मौजूदा टाइलों से जुड़ना होगा",
    "creating-words-4": "सभी बनाए गए शब्द वैध शब्दकोश शब्द होने चाहिए",
    "submitting-move": "3. अपनी चाल जमा करना:",
    "submitting-move-1": "अपनी टाइलें रखने के बाद, \"जमा करें\" बटन पर क्लिक करें",
    "submitting-move-2": "अमान्य शब्दों को अस्वीकार कर दिया जाएगा और टाइलें आपके रैक में वापस कर दी जाएंगी",
    "submitting-move-3": "अंकों की स्वचालित रूप से गणना की जाएगी और आपके स्कोर में जोड़ा जाएगा",
    "exchanging-tiles": "4. टाइलें एक्सचेंज करना:",
    "exchanging-tiles-1": "एक्सचेंज शुरू करने के लिए \"एक्सचेंज पोर्टल सक्रिय करें\" पर क्लिक करें",
    "exchanging-tiles-2": "अवांछित टाइलों को पोर्टल में ड्रैग करें",
    "exchanging-tiles-3": "आप समान संख्या में नई टाइलें प्राप्त करेंगे",
    "exchanging-tiles-4": "यह आपकी बारी के रूप में गिना जाता है",
    "skipping-end": "5. बारी छोड़ना और खेल समाप्त:",
    "skipping-end-1": "यदि आप एक वैध चाल नहीं कर सकते हैं तो \"बारी छोड़ें\" का उपयोग करें",
    "skipping-end-2": "जब सभी टाइलें उपयोग हो जाएं या दोनों खिलाड़ी लगातार दो बार छोड़ें तो खेल समाप्त हो जाता है",
    "skipping-end-3": "आपका स्कोर अक्षरों के मूल्यों और बोनस वर्गों पर आधारित है",
    
    // Dynamic content (generated by JavaScript)
    "console": "कंसोल",
    "copy-all": "सभी कॉपी करें",
    "hint-short-words": "'QI', 'ZA' और 'JO' जैसे छोटे शब्द वैध और उपयोगी हैं।",
    
    // Toast/Alert messages
    "invalid-word": "अलश्कुद शब्द! कृपया पुनः प्रयास करें।",
    "copied-clipboard": "कंसोल कौ बोर्ड तक कॉपी किया गया!",
    "no-messages-copy": "कॉपी करने के लिए कोई संदेश नहीं",
    "place-tiles-first": "कृपया पहले कुछ टाइलें रखें!",
    
    // Game messages
    "click-change-language": "भाषा बदलने के लिए क्लिक करें"
  },
  
  zh: {
    // Headers and Titles
    "definitions-history": "定义历史",
    "game-info": "游戏信息",
    "scores": "分数",
    "player": "玩家",
    "computer": "电脑",
    "tiles-remaining": "剩余瓷砖",
    "exchange-tiles": "交换瓷砖",
    "activate-exchange": "激活交换门户",
    "exchange-instructions": "将瓷砖拖到此处进行交换",
    
    // Buttons
    "print-history": "打印定义历史（显示单词定义）",
    "submit": "提交",
    "shuffle-rack": "洗牌架",
    "skip-turn": "跳过回合",
    "how-to-play": "如何玩",
    "quit-game": "退出/结束游戏",
    "close-menu": "关闭菜单",
    
    // Mobile Notifications
    "landscape-notice": "为了获得最佳体验，请将设备旋转到横向模式",
    "scroll-notice": "您可以向上和向下滚动以访问您的架子、游戏控制和移动历史",
    "instruction-notice": "开始前请在菜单中阅读\"如何玩\"",
    
    // Instructions
    "how-to-play-title": "如何玩",
    "playing-tiles": "1. 放置瓷砖:",
    "playing-tiles-1": "在桌面上：从您的架子中点击并拖动瓷砖到游戏板",
    "playing-tiles-2": "在手机上：触摸并按住瓷砖1秒钟，然后拖动放置",
    "playing-tiles-3": "要移除瓷砖，请将其拖回到您的架子",
    "creating-words": "2. 创建单词:",
    "creating-words-1": "水平放置瓷砖（从左到右）或垂直放置（从上到下）",
    "creating-words-2": "第一个单词必须穿过中心星星",
    "creating-words-3": "新单词必须连接到游戏板上现有的瓷砖",
    "creating-words-4": "所有形成的单词都必须是有效的字典单词",
    "submitting-move": "3. 提交您的移动:",
    "submitting-move-1": "放置瓷砖后，单击\"提交\"按钮",
    "submitting-move-2": "无效单词将被拒绝，瓷砖将返回到您的架子",
    "submitting-move-3": "积分将自动计算并添加到您的分数中",
    "exchanging-tiles": "4. 交换瓷砖:",
    "exchanging-tiles-1": "单击\"激活交换门户\"开始交换",
    "exchanging-tiles-2": "将不需要的瓷砖拖到门户",
    "exchanging-tiles-3": "您将收到相同数量的新瓷砖",
    "exchanging-tiles-4": "这算作您的回合",
    "skipping-end": "5. 跳过和游戏结束:",
    "skipping-end-1": "如果您无法进行有效的移动，请使用\"跳过回合\"",
    "skipping-end-2": "当所有瓷砖都被使用或两个玩家连续跳过两次时，游戏结束",
    "skipping-end-3": "您的分数基于字母值和奖励方格",
    
    // Dynamic content (generated by JavaScript)
    "console": "控制台",
    "copy-all": "全部复制",
    "hint-short-words": "'QI'、'ZA' 和 'JO' 等短单词是有效且有用的。",
    
    // Toast/Alert messages
    "invalid-word": "无效单词！请重新尝试。",
    "copied-clipboard": "控制台已複制到剪貼板！",
    "no-messages-copy": "没有要複制的消息",
    "place-tiles-first": "請先放置一些瞏火！",
    
    // Game messages
    "click-change-language": "点击更改语言"
  }
};

// Function to get translation for a key
function t(key, lang = getCurrentLanguage()) {
  return translations[lang]?.[key] || translations.en[key] || key;
}

// Function to detect current language from URL/page
function getCurrentLanguage() {
  const url = window.location.pathname;
  if (url.includes('spanish.html')) return 'es';
  if (url.includes('french.html')) return 'fr';
  if (url.includes('hindi.html')) return 'hi';
  if (url.includes('mandarin.html')) return 'zh';
  return 'en'; // Default to English
}

// Function to apply translations to the entire page
function applyTranslations() {
  const lang = getCurrentLanguage();
  
  // Find all elements with data-i18n attribute and translate them
  document.querySelectorAll('[data-i18n]').forEach(element => {
    const key = element.getAttribute('data-i18n');
    const translation = t(key, lang);
    
    // For elements that contain only text or have empty content
    if (element.childNodes.length === 0 || (element.childNodes.length === 1 && element.childNodes[0].nodeType === 3)) {
      element.textContent = translation;
    } else {
      // For elements with children, replace only the first text node or all text content
      let found = false;
      for (let i = 0; i < element.childNodes.length; i++) {
        if (element.childNodes[i].nodeType === 3) {
          // Text node
          element.childNodes[i].textContent = translation;
          found = true;
          break;
        }
      }
      // If no text node found as first child, just set text content
      if (!found) {
        element.textContent = translation;
      }
    }
  });
  
  // Find all elements with data-i18n-label attribute and update their aria-label
  document.querySelectorAll('[data-i18n-label]').forEach(element => {
    const key = element.getAttribute('data-i18n-label');
    element.setAttribute('aria-label', t(key, lang));
  });
  
  // Update close menu buttons
  const closeMenuButtons = document.querySelectorAll('[aria-label="Close menu"]');
  closeMenuButtons.forEach(btn => {
    btn.setAttribute('aria-label', t('close-menu', lang));
  });
}


// Auto-apply translations when DOM is ready
document.addEventListener('DOMContentLoaded', applyTranslations);
